# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Lint with ruff
      run: uv tool run ruff check 
    - name: Check formatting
      run: uv tool run ruff format --check
    - name: Check types
      run: uv tool run ty check
    - name: Test with pytest
      run: uv run pytest --pyargs py_preference
